General enhancements to the single-agent environment
madras-simulator/MADRaS pull request #41
Opened 2020-02-11 02:47 UTC by Santara

2020-02-11 15:37 UTC, rudrasohan requested changes
Some minor suggestions.

2020-02-11 15:37 UTC, rudrasohan commented on MADRaS/__init__.py
> +#     entry_point='MADRaS.envs:MadrasEnv',
Don't comment out this one as otherwise, the environment registration will not work.

2020-02-11 15:37 UTC, rudrasohan commented on MADRaS/utils/done_handler.py
> +            print("Done: Race over in {} steps!".format(self.num_steps))
Can we remove all the prints from this file and replace them with logs.

2020-02-12 04:30 UTC, Santara commented on MADRaS/__init__.py
> +#     entry_point='MADRaS.envs:MadrasEnv',
I did this by mistake - will fix it.

2020-02-12 04:31 UTC, Santara commented on MADRaS/utils/done_handler.py
> +            print("Done: Race over in {} steps!".format(self.num_steps))
will do :+1:

2020-04-03 15:16 UTC, rudrasohan approved these changes
Awesome :+1:

2020-04-04 05:25 UTC, merged